# WiFi + API config

SSID = "SSID_NAME"
PASSWORD = "WIFI_PASSWORD"

OW_API_KEY = "API_KEYS"
LAT = "LAT_TO_YOUR_LOCATION_AS_NUMBER"
LON = "LONG_TO_YOUR_LOCATION_AS_NUMBER"

UPDATE_INTERVAL = 120  # seconds
HISTORY_SIZE = 10
